### ISSUE TITLE
Repetition of rerootingMethod

### ISSUE THREAD

**Issue by TGuillerme** [graemetlloyd/Claddis#2]
Hi Graeme, 

I was just playing with the `AncStateEstMatrix` function and found a little slow. It seems there is a little typo that makes the function calculates the ancestral states twice:
```
# Get likelihoods for each state in taxa and ancestors:
state.likelihoods <- rerootingMethod(chartree, tipvals.mat, model=mymodel)$marginal.anc
```
I guess the one lines 125-126 is extra since the one lines 131-132 comes after the `chartree` with no nodes (`chartree$node.label<-NULL`).

Cheers!

Thomas.

**Comment by graemetlloyd** [comment]
Oops. Good catch. And I think I had that NULL line because of something you sent before.

Corrected github version now.

G

**Comment by TGuillerme** [comment]
Yeah, if I remember well the `NULL` thingy was due to a bug in `rerootingMethod` that seems to freak out if the input tree had node names.
T.
