### ISSUE TITLE
Suggestion for ReadMorphNexus

### ISSUE THREAD

**Issue by TGuillerme** [graemetlloyd/Claddis#5]
Hi Graeme,

Just a quick suggestion for allowing `ReadMorphNexus` to detect lines that have too many/few characters. You could add the following line 613:
```r
    # Little test to check the number of characters on each line is the same as nchar:
    wrong.character.number <- which(unlist(lapply(discrete.matrix, length)) != nchar)
    if(length(wrong.character.number) > 0) stop(paste("Taxa number", wrong.character.number, "has too many or too few characters.\n"))
```
This way it will actually print out the lines that have too many/few characters which makes it easier to find the taxa that are messing up the data!

Cheers,

Thomas.

**Comment by TGuillerme** [comment]
Hi Graeme,

Another suggestion for treating gaps as `-` rather than `NA`: https://github.com/TGuillerme/Claddis/commit/9a1cc6bb5c9757e8396dc999ca1df7a1bd499eb5

Cheers,

Thomas.

**Comment by TGuillerme** [comment]
Hi Graeme,

I've also modified `MakeMorphMatrix` and `WriteMorphNexus` to deal with inapplicable tokens (`"-"`): https://github.com/TGuillerme/Claddis/commit/c8cee8effd30437e70bb0673dbc4b071a3252712

Cheers,

Thomas.

**Comment by graemetlloyd** [comment]
Thanks Thomas. As you know by now I decided to represent inapplicable states with empty strings ("") so am closing this issue.
